# Generated by Django 3.2.10 on 2022-01-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('srn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=130)),
                ('image', models.ImageField(upload_to='images')),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
