# Generated by Django 3.2.10 on 2022-01-07 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StoriesApp', '0002_auto_20220103_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
